name: Build package

on:
  workflow_call:
    inputs:
      command:
        required: false
        type: string
        default: ./gen-package.sh
      repo_bucket:
        required: false
        type: string
        default: sensorgnome-982081078525-us-east-1-an
      repo_region:
        required: false
        type: string
        default: us-east-1
      repo_codename:
        required: false
        type: string
        default: booktest
      aws_role:
        required: false
        type: string
        default: arn:aws:iam::982081078525:role/GitHub-automations
      dependency:
        required: false
        type: string
        default: ""
      gpg_key_id:
        required: false
        type: string
        default: 1DC0C66E4594570A
    secrets:
      GPG_PRIVATE_KEY:
        required: true
      GPG_PASSPHRASE:
        required: true
      CLAIM_CERT:
        required: false
      CLAIM_PRIVATE_KEY:
        required: false

permissions:
  id-token: write
  contents: write

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .

      - name: Install PAM auth dependency
        if: ${{inputs.dependency}}
        run: sudo apt install -y ${{ inputs.dependency }}
      
      # To export key: gpg --list-secret-keys --keyid-format LONG; gpg --export-secret-keys --armor {your_keyId}
      - name: Install GPG key to sign package
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      
      # Add in secrets if needed.
      - name: Inject build secrets
        run: |
          [ -n "$CLAIM_CERT" ] && printf '%s' "$CLAIM_CERT" > provisioning/claim-cert.pem || true
          [ -n "$CLAIM_PRIVATE_KEY" ] && printf '%s' "$CLAIM_PRIVATE_KEY" > provisioning/claim-private-key.pem || true
        env:
          CLAIM_CERT: ${{ secrets.CLAIM_CERT }}
          CLAIM_PRIVATE_KEY: ${{ secrets.CLAIM_PRIVATE_KEY }}

      - name: Configure AWS Credentials
        # See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{inputs.aws_role}}
          role-session-name: GithubActionsMotus
          aws-region: ${{inputs.repo_region}}

      - name: Set up QEMU for ARM emulation
        uses: docker/setup-qemu-action@v3

      - name: Generate .deb packages
        run: ${{ inputs.command }}
        shell: bash

      - run: ls -ls packages

      # Upload github artifacts for debugging purposes
      - uses: actions/upload-artifact@v4
        with:
          name: deb-packages
          path: packages

      - name: Insert .debs into repository
        # GPG_TTY needed to avoid `gpg: signing failed: Inappropriate ioctl for device`
        run: |
          for f in packages/*.deb; do
            aws s3 cp "$f" "s3://${{ inputs.repo_bucket }}/pool/${{ inputs.repo_codename }}/"
          done